// ----------------------------------------------------------------------------
// TENNIS MATRIX AUDIT — schema.
//
// The Audit's own tables, defined here in Drizzle against this workspace's
// DATABASE_URL. They are additive: no table below is shared with, or renamed
// from, the AI prediction engine's own schema, and nothing here touches
// predictions, historical_matches, parlay_* or any existing table.
//
// Column names, types and nullability are the Audit's existing production shape,
// so the frozen engine's row handling keeps working unchanged -- the engine reads
// and writes these column names directly through PipelineDeps.
//
// Generated from the Audit's live schema and then reviewed by hand; the unique
// constraints below are the ones the pipeline actually depends on:
//   * audit_stage_runs (audit_run_id, stage) — one canonical row per stage per run
//   * audit_coverage   (audit_run_id, player_side)
//   * metric_coverage_rates (metric_code, player_side, audit_run_id)
//   * audit_runs (match_id, run_number) — ensureRun() never resets run_number
// ----------------------------------------------------------------------------
import { sql } from "drizzle-orm";
import {
  boolean, customType, date, doublePrecision, integer, jsonb, numeric, pgTable,
  text, timestamp, uniqueIndex, uuid,
} from "drizzle-orm/pg-core";


export const auditCoverage = pgTable("audit_coverage", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  auditRunId: uuid("audit_run_id").notNull(),
  playerSide: text("player_side").notNull(),
  directCount: integer("direct_count").default(0).notNull(),
  reconstructedCount: integer("reconstructed_count").default(0).notNull(),
  partialCount: integer("partial_count").default(0).notNull(),
  unavailableCount: integer("unavailable_count").default(0).notNull(),
  excludedCount: integer("excluded_count").default(0).notNull(),
  totalCount: integer("total_count").default(0).notNull(),
  usableCoveragePercent: numeric("usable_coverage_percent").default("0").notNull(),
  executionCompletionPercent: numeric("execution_completion_percent").default("0").notNull(),
  recordedAt: timestamp("recorded_at", { withTimezone: true }).defaultNow().notNull(),
  userId: uuid("user_id"),
}, (table) => ({
  auditCoverageRunSideKey: uniqueIndex("audit_coverage_audit_run_id_player_side_key").on(table.auditRunId, table.playerSide),
}));

export const auditRuns = pgTable("audit_runs", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  matchId: uuid("match_id").notNull(),
  runNumber: integer("run_number").default(1).notNull(),
  researchLockAt: timestamp("research_lock_at", { withTimezone: true }),
  independentDecisionCommittedAt: timestamp("independent_decision_committed_at", { withTimezone: true }),
  matrixRevealedAt: timestamp("matrix_revealed_at", { withTimezone: true }),
  independentWinner: text("independent_winner"),
  independentLow: numeric("independent_low"),
  independentHigh: numeric("independent_high"),
  calibratedLow: numeric("calibrated_low"),
  calibratedHigh: numeric("calibrated_high"),
  effectiveEvidenceCount: integer("effective_evidence_count").default(0).notNull(),
  rawSignalCount: integer("raw_signal_count").default(0).notNull(),
  status: text("status").default('RUNNING').notNull(),
  staleReason: text("stale_reason"),
  verificationVersionId: uuid("verification_version_id"),
  disagreementVersionId: uuid("disagreement_version_id"),
  metricsVersionId: uuid("metrics_version_id"),
  calibrationVersionId: uuid("calibration_version_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  independentMethodId: uuid("independent_method_id"),
  independentMethodVersion: text("independent_method_version"),
  independentInputs: jsonb("independent_inputs").default(sql`'{}'::jsonb`).notNull(),
  leaseOwner: text("lease_owner"),
  leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }),
  heartbeatAt: timestamp("heartbeat_at", { withTimezone: true }),
  independentWinnerId: uuid("independent_winner_id"),
  independentWinnerSide: text("independent_winner_side"),
}, (table) => ({
  auditRunsMatchRunNumberKey: uniqueIndex("audit_runs_match_id_run_number_key").on(table.matchId, table.runNumber),
}));

export const auditStageRuns = pgTable("audit_stage_runs", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  auditRunId: uuid("audit_run_id").notNull(),
  matchId: uuid("match_id"),
  stage: text("stage").notNull(),
  stageOrder: integer("stage_order").default(0).notNull(),
  status: text("status").default('PENDING').notNull(),
  attempts: integer("attempts").default(0).notNull(),
  startedAt: timestamp("started_at", { withTimezone: true }),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  detail: jsonb("detail").default(sql`'{}'::jsonb`).notNull(),
  doneCount: integer("done_count").default(0).notNull(),
  totalCount: integer("total_count").default(0).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  heartbeatAt: timestamp("heartbeat_at", { withTimezone: true }),
}, (table) => ({
  auditStageRunsRunStageKey: uniqueIndex("audit_stage_runs_audit_run_id_stage_key").on(table.auditRunId, table.stage),
}));

export const calibrationBuckets = pgTable("calibration_buckets", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  calibrationVersionId: uuid("calibration_version_id").notNull(),
  bucketCode: text("bucket_code").notNull(),
  bucketLabel: text("bucket_label").notNull(),
  wpMin: numeric("wp_min").notNull(),
  wpMax: numeric("wp_max").notNull(),
  wins: integer("wins").default(0).notNull(),
  graded: integer("graded").default(0).notNull(),
  smallSample: boolean("small_sample").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const calibrationVersions = pgTable("calibration_versions", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  versionNumber: integer("version_number").default(1).notNull(),
  label: text("label").notNull(),
  masterSequenceCount: integer("master_sequence_count").default(0).notNull(),
  gradedSampleCount: integer("graded_sample_count").default(0).notNull(),
  isActive: boolean("is_active").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const disagreementResults = pgTable("disagreement_results", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  auditRunId: uuid("audit_run_id").notNull(),
  ruleId: uuid("rule_id"),
  ruleCode: text("rule_code").notNull(),
  ruleName: text("rule_name").notNull(),
  p1Risk: text("p1_risk"),
  p2Risk: text("p2_risk"),
  supportingEvidence: text("supporting_evidence"),
  opposingEvidence: text("opposing_evidence"),
  contradictionSeverity: text("contradiction_severity"),
  finalEffect: text("final_effect"),
  status: text("status").default('NOT STARTED').notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  unavailableReason: text("unavailable_reason"),
  unavailableDetail: text("unavailable_detail"),
  providerError: text("provider_error"),
  sources: jsonb("sources").default(sql`'[]'::jsonb`).notNull(),
  missingInputs: jsonb("missing_inputs").default(sql`'[]'::jsonb`).notNull(),
  sourceAttempts: jsonb("source_attempts").default(sql`'[]'::jsonb`).notNull(),
  reconstructionAttempted: boolean("reconstruction_attempted").default(false).notNull(),
  reconstructionReason: text("reconstruction_reason"),
  reconstructionResult: text("reconstruction_result"),
  retrievedAt: timestamp("retrieved_at", { withTimezone: true }),
});

export const executionLogs = pgTable("execution_logs", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  auditRunId: uuid("audit_run_id"),
  matchId: uuid("match_id"),
  stage: text("stage").notNull(),
  ruleCode: text("rule_code"),
  playerSide: text("player_side"),
  input: jsonb("input"),
  output: jsonb("output"),
  source: text("source"),
  status: text("status").notNull(),
  matrixVisible: boolean("matrix_visible").default(false).notNull(),
  ruleVersion: text("rule_version"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const finalDecisions = pgTable("final_decisions", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  auditRunId: uuid("audit_run_id").notNull(),
  finalAuditColor: text("final_audit_color").default('INCOMPLETE').notNull(),
  finalSelection: text("final_selection"),
  action: text("action"),
  gateReport: jsonb("gate_report").default(sql`'{}'::jsonb`).notNull(),
  completionPercent: numeric("completion_percent").default("0").notNull(),
  auditComplete: boolean("audit_complete").default(false).notNull(),
  matrixFirewallValid: boolean("matrix_firewall_valid").default(true).notNull(),
  calibrationBucket: text("calibration_bucket"),
  verifiedWinRate: numeric("verified_win_rate"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  selectedPlayerId: uuid("selected_player_id"),
});

export const matchIdentityRecords = pgTable("match_identity_records", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  matchId: uuid("match_id").notNull(),
  field: text("field").notNull(),
  claimedValue: text("claimed_value"),
  verifiedValue: text("verified_value"),
  status: text("status").default('NOT STARTED').notNull(),
  note: text("note"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const matches = pgTable("matches", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  canonicalKey: text("canonical_key").notNull(),
  player1Name: text("player1_name").notNull(),
  player2Name: text("player2_name").notNull(),
  player1Id: uuid("player1_id"),
  player2Id: uuid("player2_id"),
  tournamentId: uuid("tournament_id"),
  tournamentName: text("tournament_name"),
  eventLevel: text("event_level"),
  round: text("round"),
  scheduledDate: date("scheduled_date"),
  surface: text("surface"),
  indoor: boolean("indoor"),
  bestOf: integer("best_of"),
  identityStatus: text("identity_status").default('UNVERIFIED').notNull(),
  surfaceStatus: text("surface_status").default('UNVERIFIED').notNull(),
  matchStatus: text("match_status").default('RUNNING').notNull(),
  activeSummaryVersionId: uuid("active_summary_version_id"),
  resultStatus: text("result_status").default('UNKNOWN').notNull(),
  actualWinner: text("actual_winner"),
  finalScore: text("final_score"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  tournamentTimezone: text("tournament_timezone"),
  scheduledLocalAt: timestamp("scheduled_local_at", { withTimezone: true }),
  scheduledUtcAt: timestamp("scheduled_utc_at", { withTimezone: true }),
  actualFirstServeAt: timestamp("actual_first_serve_at", { withTimezone: true }),
  resultRecordedAt: timestamp("result_recorded_at", { withTimezone: true }),
  slateId: uuid("slate_id"),
});

export const metricCoverageRates = pgTable("metric_coverage_rates", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  metricCode: text("metric_code").notNull(),
  playerSide: text("player_side").notNull(),
  treatment: text("treatment").notNull(),
  auditRunId: uuid("audit_run_id").notNull(),
  usable: boolean("usable").default(false).notNull(),
  recordedAt: timestamp("recorded_at", { withTimezone: true }).defaultNow().notNull(),
  userId: uuid("user_id"),
}, (table) => ({
  metricCoverageRatesKey: uniqueIndex("metric_coverage_rates_metric_code_player_side_audit_run_id_key").on(table.metricCode, table.playerSide, table.auditRunId),
}));

export const metricEvidenceStore = pgTable("metric_evidence_store", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id"),
  metricCode: text("metric_code").notNull(),
  metricName: text("metric_name").notNull(),
  playerName: text("player_name").notNull(),
  opponentName: text("opponent_name"),
  tournament: text("tournament"),
  surface: text("surface"),
  asOfDate: date("as_of_date").notNull(),
  treatment: text("treatment").notNull(),
  valueText: text("value_text"),
  reliability: doublePrecision("reliability"),
  sampleLabel: text("sample_label"),
  evidenceFamily: text("evidence_family"),
  sourceIds: text("source_ids").array().notNull(),
  sources: jsonb("sources").default(sql`'[]'::jsonb`).notNull(),
  inputObservationIds: text("input_observation_ids").array().notNull(),
  formula: text("formula"),
  unavailableReason: text("unavailable_reason"),
  validFrom: date("valid_from"),
  validUntil: timestamp("valid_until", { withTimezone: true }),
  computedAt: timestamp("computed_at", { withTimezone: true }).defaultNow().notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const metricRegistry = pgTable("metric_registry", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  metricCode: text("metric_code").notNull(),
  metricName: text("metric_name").notNull(),
  lifecycleStatus: text("lifecycle_status").default('ACTIVE').notNull(),
  tourEligibility: text("tour_eligibility").array().notNull(),
  evidenceFamily: text("evidence_family"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  userId: uuid("user_id"),
}, (table) => ({
  metricRegistryCodeKey: uniqueIndex("metric_registry_metric_code_key").on(table.metricCode),
}));

export const metricResults = pgTable("metric_results", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  auditRunId: uuid("audit_run_id").notNull(),
  metricCode: text("metric_code").notNull(),
  metricName: text("metric_name").notNull(),
  category: text("category"),
  p1Value: text("p1_value"),
  p2Value: text("p2_value"),
  p1Status: text("p1_status").default('NOT STARTED').notNull(),
  p2Status: text("p2_status").default('NOT STARTED').notNull(),
  differential: text("differential"),
  surfaceAdjustedDiff: text("surface_adjusted_diff"),
  treatment: text("treatment"),
  reliability: numeric("reliability"),
  sample: text("sample"),
  sources: jsonb("sources").default(sql`'[]'::jsonb`).notNull(),
  evidenceFamily: text("evidence_family"),
  matrixDerived: boolean("matrix_derived").default(false).notNull(),
  status: text("status").default('NOT STARTED').notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  p1Treatment: text("p1_treatment").default('UNAVAILABLE').notNull(),
  p2Treatment: text("p2_treatment").default('UNAVAILABLE').notNull(),
  unavailableReason: text("unavailable_reason"),
  unavailableDetail: text("unavailable_detail"),
  providerError: text("provider_error"),
  missingInputs: jsonb("missing_inputs").default(sql`'[]'::jsonb`).notNull(),
  sourceAttempts: jsonb("source_attempts").default(sql`'[]'::jsonb`).notNull(),
  reconstructionAttempted: boolean("reconstruction_attempted").default(false).notNull(),
  reconstructionReason: text("reconstruction_reason"),
  reconstructionResult: text("reconstruction_result"),
  retrievedAt: timestamp("retrieved_at", { withTimezone: true }),
  p1UnavailableReason: text("p1_unavailable_reason"),
  p2UnavailableReason: text("p2_unavailable_reason"),
  p1ProviderError: text("p1_provider_error"),
  p2ProviderError: text("p2_provider_error"),
  p1RetrievedAt: timestamp("p1_retrieved_at", { withTimezone: true }),
  p2RetrievedAt: timestamp("p2_retrieved_at", { withTimezone: true }),
});

export const parsedSummaryFields = pgTable("parsed_summary_fields", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  summaryVersionId: uuid("summary_version_id").notNull(),
  fieldKey: text("field_key").notNull(),
  rawValue: text("raw_value"),
  normalizedValue: text("normalized_value"),
  extractionStatus: text("extraction_status").default('DIRECT').notNull(),
  confidence: numeric("confidence"),
  corrected: boolean("corrected").default(false).notNull(),
  pageNumber: integer("page_number"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const predictionSlates = pgTable("prediction_slates", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  slateNumber: integer("slate_number").notNull(),
  label: text("label"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  retiredAt: timestamp("retired_at", { withTimezone: true }),
  retiredReason: text("retired_reason"),
});

export const reconstructionResults = pgTable("reconstruction_results", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  auditRunId: uuid("audit_run_id").notNull(),
  metricCode: text("metric_code").notNull(),
  playerSide: text("player_side").notNull(),
  formula: text("formula"),
  inputs: jsonb("inputs").default(sql`'[]'::jsonb`).notNull(),
  assumptions: text("assumptions"),
  output: text("output"),
  reliability: numeric("reliability"),
  status: text("status").default('NOT STARTED').notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  formulaVersionId: uuid("formula_version_id"),
  formulaVersionLabel: text("formula_version_label"),
  calculation: text("calculation"),
  sourceRefs: jsonb("source_refs").default(sql`'[]'::jsonb`).notNull(),
  unavailableReason: text("unavailable_reason"),
  providerError: text("provider_error"),
  missingInputs: jsonb("missing_inputs").default(sql`'[]'::jsonb`).notNull(),
  sourceAttempts: jsonb("source_attempts").default(sql`'[]'::jsonb`).notNull(),
  reconstructionAttempted: boolean("reconstruction_attempted").default(true).notNull(),
  reconstructionReason: text("reconstruction_reason"),
  reconstructionResult: text("reconstruction_result"),
  retrievedAt: timestamp("retrieved_at", { withTimezone: true }),
});

export const resultGrades = pgTable("result_grades", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  matchId: uuid("match_id").notNull(),
  auditRunId: uuid("audit_run_id"),
  actualWinner: text("actual_winner"),
  resultType: text("result_type").default('WIN').notNull(),
  matrixPredictedWinner: text("matrix_predicted_winner"),
  matrixWp: numeric("matrix_wp"),
  matrixPredictionResult: text("matrix_prediction_result").default('NOT GRADED').notNull(),
  independentWinner: text("independent_winner"),
  independentLow: numeric("independent_low"),
  independentHigh: numeric("independent_high"),
  independentAuditResult: text("independent_audit_result").default('NOT GRADED').notNull(),
  finalSelection: text("final_selection"),
  finalSelectionResult: text("final_selection_result").default('NOT GRADED').notNull(),
  auditColor: text("audit_color"),
  correctionPattern: text("correction_pattern").default('UNCLASSIFIED').notNull(),
  countedInMatrixCalibration: boolean("counted_in_matrix_calibration").default(false).notNull(),
  note: text("note"),
  gradedAt: timestamp("graded_at", { withTimezone: true }).defaultNow().notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const ruleDocumentVersions = pgTable("rule_document_versions", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  documentId: uuid("document_id").notNull(),
  versionNumber: integer("version_number").default(1).notNull(),
  sourceFilename: text("source_filename"),
  rawText: text("raw_text"),
  pagesDetected: integer("pages_detected"),
  headingsDetected: integer("headings_detected"),
  expectedRules: integer("expected_rules").default(0).notNull(),
  parsedRules: integer("parsed_rules").default(0).notNull(),
  unmappedRules: integer("unmapped_rules").default(0).notNull(),
  parserConfidence: numeric("parser_confidence"),
  activationStatus: text("activation_status").default('BLOCKED').notNull(),
  isActive: boolean("is_active").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const ruleDocuments = pgTable("rule_documents", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  docType: text("doc_type").notNull(),
  title: text("title").notNull(),
  activeVersionId: uuid("active_version_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const rules = pgTable("rules", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  versionId: uuid("version_id").notNull(),
  ruleCode: text("rule_code").notNull(),
  ruleName: text("rule_name").notNull(),
  category: text("category"),
  body: text("body"),
  severity: text("severity").default('STANDARD').notNull(),
  blocking: boolean("blocking").default(false).notNull(),
  mappingStatus: text("mapping_status").default('REQUIRES HUMAN RULE MAPPING').notNull(),
  machineLogic: jsonb("machine_logic"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const sourceConflicts = pgTable("source_conflicts", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  auditRunId: uuid("audit_run_id").notNull(),
  dataKey: text("data_key").notNull(),
  critical: boolean("critical").default(false).notNull(),
  values: jsonb("values").default(sql`'[]'::jsonb`).notNull(),
  resolutionStatus: text("resolution_status").default('UNRESOLVED').notNull(),
  resolutionReason: text("resolution_reason"),
  selectedValue: text("selected_value"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const sourceObservations = pgTable("source_observations", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id"),
  sourceId: text("source_id").notNull(),
  sourceName: text("source_name").notNull(),
  sourceUrl: text("source_url"),
  sourceRecordKey: text("source_record_key"),
  playerName: text("player_name"),
  opponentName: text("opponent_name"),
  tournament: text("tournament"),
  eventDate: date("event_date"),
  surface: text("surface"),
  observationType: text("observation_type").notNull(),
  observationKey: text("observation_key").notNull(),
  numericValue: doublePrecision("numeric_value"),
  textValue: text("text_value"),
  unit: text("unit"),
  sampleLabel: text("sample_label"),
  windowStart: date("window_start"),
  windowEnd: date("window_end"),
  retrievedAt: timestamp("retrieved_at", { withTimezone: true }).defaultNow().notNull(),
  sourcePublishedAt: timestamp("source_published_at", { withTimezone: true }),
  rawPayload: jsonb("raw_payload"),
  provenance: jsonb("provenance").default(sql`'{}'::jsonb`).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const sourceSnapshots = pgTable("source_snapshots", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  auditRunId: uuid("audit_run_id").notNull(),
  sourceId: uuid("source_id"),
  sourceName: text("source_name").notNull(),
  dataKey: text("data_key").notNull(),
  playerSide: text("player_side"),
  rawValue: text("raw_value"),
  normalizedValue: text("normalized_value"),
  retrievedAt: timestamp("retrieved_at", { withTimezone: true }).defaultNow().notNull(),
  postStart: boolean("post_start").default(false).notNull(),
  excluded: boolean("excluded").default(false).notNull(),
  reliability: numeric("reliability"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const stressResults = pgTable("stress_results", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  auditRunId: uuid("audit_run_id").notNull(),
  testCode: text("test_code").notNull(),
  testName: text("test_name").notNull(),
  winnerBefore: text("winner_before"),
  winnerAfter: text("winner_after"),
  rangeBefore: text("range_before"),
  rangeAfter: text("range_after"),
  outcome: text("outcome").default('NOT STARTED').notNull(),
  status: text("status").default('NOT STARTED').notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  unavailableReason: text("unavailable_reason"),
  unavailableDetail: text("unavailable_detail"),
  providerError: text("provider_error"),
  sources: jsonb("sources").default(sql`'[]'::jsonb`).notNull(),
  missingInputs: jsonb("missing_inputs").default(sql`'[]'::jsonb`).notNull(),
  sourceAttempts: jsonb("source_attempts").default(sql`'[]'::jsonb`).notNull(),
  reconstructionAttempted: boolean("reconstruction_attempted").default(false).notNull(),
  reconstructionReason: text("reconstruction_reason"),
  reconstructionResult: text("reconstruction_result"),
  retrievedAt: timestamp("retrieved_at", { withTimezone: true }),
  p1OutcomeWhenStressed: text("p1_outcome_when_stressed"),
  p2OutcomeWhenStressed: text("p2_outcome_when_stressed"),
  p1SupportPercentBefore: numeric("p1_support_percent_before"),
  p1SupportPercentAfter: numeric("p1_support_percent_after"),
  p2SupportPercentBefore: numeric("p2_support_percent_before"),
  p2SupportPercentAfter: numeric("p2_support_percent_after"),
  comparativeRobustness: text("comparative_robustness"),
});

export const summaryUploads = pgTable("summary_uploads", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  filename: text("filename").notNull(),
  pageCount: integer("page_count"),
  parseStatus: text("parse_status").default('NOT STARTED').notNull(),
  rawText: text("raw_text"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  pagesProcessed: integer("pages_processed").default(0).notNull(),
  pagesVision: integer("pages_vision").default(0).notNull(),
  pagesFailed: integer("pages_failed").default(0).notNull(),
  extractionStatus: text("extraction_status").default('PENDING').notNull(),
});

export const summaryVersions = pgTable("summary_versions", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  matchId: uuid("match_id").notNull(),
  uploadId: uuid("upload_id").notNull(),
  versionNumber: integer("version_number").default(1).notNull(),
  pageNumber: integer("page_number"),
  isActive: boolean("is_active").default(true).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const truthEngineCalibrationObservations = pgTable("truth_engine_calibration_observations", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  matchId: uuid("match_id").notNull(),
  auditRunId: uuid("audit_run_id").notNull(),
  slateId: uuid("slate_id"),
  runNumber: integer("run_number").default(0).notNull(),
  predictedAt: timestamp("predicted_at", { withTimezone: true }),
  scheduledDate: date("scheduled_date"),
  player1Name: text("player1_name").notNull(),
  player2Name: text("player2_name").notNull(),
  selectedPlayer: text("selected_player").notNull(),
  decisionOutcome: text("decision_outcome").notNull(),
  evidenceSupportPercent: numeric("evidence_support_percent"),
  directionalFamilies: integer("directional_families"),
  supportingFamilies: text("supporting_families").array().notNull(),
  contradictingFamilies: text("contradicting_families").array().notNull(),
  neutralFamilies: text("neutral_families").array().notNull(),
  conflictedFamilies: text("conflicted_families").array().notNull(),
  supportingFamilyCount: integer("supporting_family_count"),
  contradictingFamilyCount: integer("contradicting_family_count"),
  corroborated: boolean("corroborated"),
  stability: text("stability"),
  verificationResult: text("verification_result"),
  disagreementResult: text("disagreement_result"),
  underdogResult: text("underdog_result"),
  stressResult: text("stress_result"),
  evidenceCoveragePercent: numeric("evidence_coverage_percent"),
  evidenceCoverageUsable: integer("evidence_coverage_usable"),
  evidenceCoverageExpected: integer("evidence_coverage_expected"),
  actualWinner: text("actual_winner").notNull(),
  resultStatus: text("result_status"),
  finalScore: text("final_score"),
  predictionOutcome: text("prediction_outcome").notNull(),
  calibrationEligible: boolean("calibration_eligible").default(false).notNull(),
  eligibilityReason: text("eligibility_reason"),
  observedAt: timestamp("observed_at", { withTimezone: true }).defaultNow().notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  player1Id: uuid("player1_id"),
  player2Id: uuid("player2_id"),
  selectedPlayerId: uuid("selected_player_id"),
  actualWinnerId: uuid("actual_winner_id"),
  tournamentName: text("tournament_name"),
  surface: text("surface"),
  eventLevel: text("event_level"),
  metricsVersionId: uuid("metrics_version_id"),
  verificationVersionId: uuid("verification_version_id"),
  disagreementVersionId: uuid("disagreement_version_id"),
  calibrationModelVersion: text("calibration_model_version"),
  featureVersion: text("feature_version"),
});

export const underdogResults = pgTable("underdog_results", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  auditRunId: uuid("audit_run_id").notNull(),
  pathwayCode: text("pathway_code").notNull(),
  pathwayName: text("pathway_name").notNull(),
  playerSide: text("player_side").notNull(),
  classification: text("classification").default('UNRESOLVED').notNull(),
  evidence: text("evidence"),
  repeatable: boolean("repeatable").default(false).notNull(),
  status: text("status").default('NOT STARTED').notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  unavailableReason: text("unavailable_reason"),
  unavailableDetail: text("unavailable_detail"),
  providerError: text("provider_error"),
  sources: jsonb("sources").default(sql`'[]'::jsonb`).notNull(),
  missingInputs: jsonb("missing_inputs").default(sql`'[]'::jsonb`).notNull(),
  sourceAttempts: jsonb("source_attempts").default(sql`'[]'::jsonb`).notNull(),
  reconstructionAttempted: boolean("reconstruction_attempted").default(false).notNull(),
  reconstructionReason: text("reconstruction_reason"),
  reconstructionResult: text("reconstruction_result"),
  retrievedAt: timestamp("retrieved_at", { withTimezone: true }),
});

export const verificationResults = pgTable("verification_results", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: uuid("user_id").notNull(),
  auditRunId: uuid("audit_run_id").notNull(),
  ruleId: uuid("rule_id"),
  ruleCode: text("rule_code").notNull(),
  ruleName: text("rule_name").notNull(),
  p1Finding: text("p1_finding"),
  p2Finding: text("p2_finding"),
  outcome: text("outcome").default('NOT STARTED').notNull(),
  severity: text("severity"),
  decisionEffect: text("decision_effect"),
  sources: jsonb("sources").default(sql`'[]'::jsonb`).notNull(),
  status: text("status").default('NOT STARTED').notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  unavailableReason: text("unavailable_reason"),
  unavailableDetail: text("unavailable_detail"),
  providerError: text("provider_error"),
  missingInputs: jsonb("missing_inputs").default(sql`'[]'::jsonb`).notNull(),
  sourceAttempts: jsonb("source_attempts").default(sql`'[]'::jsonb`).notNull(),
  reconstructionAttempted: boolean("reconstruction_attempted").default(false).notNull(),
  reconstructionReason: text("reconstruction_reason"),
  reconstructionResult: text("reconstruction_result"),
  retrievedAt: timestamp("retrieved_at", { withTimezone: true }),
});

// ----------------------------------------------------------------------------
// THE RUNTIME TENNIS INDEX.
//
// The Audit's local evidence backbone -- per-player Elo/form buckets and per-tour match
// history -- stored once, gzipped, instead of as the standalone app's 80MB Git-LFS blob
// plus a second static-asset copy. Keeping it here means one system of record rather than
// ~291MB of statistical data duplicated alongside the database, and no per-asset size cap
// to design around. Read by evidence/runtime-tennis-index-data.server.ts, which hydrates
// it into memory on first use; written only by scripts/loadAuditRuntimeIndex.ts.
// ----------------------------------------------------------------------------
export const auditRuntimeIndex = pgTable("audit_runtime_index", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  // gzip of the index JSON. bytea rather than jsonb on purpose: nothing queries inside it,
  // it is hydrated whole, and the compressed form is an order of magnitude smaller.
  payload: customType<{ data: Buffer; driverData: Buffer }>({ dataType: () => "bytea" })("payload").notNull(),
  generatedAt: timestamp("generated_at", { withTimezone: true }).defaultNow().notNull(),
  sourceDescription: text("source_description"),
  playerCount: integer("player_count"),
  matchCount: integer("match_count"),
});
